#!/bin/bash
#Script to easily compile and start the server quickly
#also starts grSim, press "q" then Enter after starting to quit


###### Variables #########################################
workingDir="$(pwd)"

###### Functions #########################################
function checkFile
{
	if [ -f server_30015 ]; then
		echo -n "Overwrite last executable \"server_30015\"? (y/n) > "
		read response
		if [ "$response" = "y" ]; then
			rm server_30015
		fi
	fi
}


###### Main ##############################################
echo -n "Do you want to start grSim? (y/n) > "
read response
killall -q -e server_30015
killall -q -e grSim
if [ "$response" = "y" ]; then
	checkFile
	if make; then
		./server_30015 &
		cd ../grSim/bin
		./grSim > logG.txt&
		echo "Press \"q\" then Enter to quit the programs"
		read response
		if [ "$response" = "q" ]; then
			killall -q -e server_30015
			killall -q -e grSim
			rm logG.txt
			#cd $workingDir
			#rm logS.txt
		fi
	else 
		echo "Error in making executable"
	fi
else
	checkFile
	make
fi

